//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaserGRBL {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaserGRBL.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 点击右键添加自定义按钮 的本地化字符串。
        /// </summary>
        internal static string AddCustomButtonsHint {
            get {
                return ResourceManager.GetString("AddCustomButtonsHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Abort current job? 的本地化字符串。
        /// </summary>
        internal static string BoxAbortProgramConfirm {
            get {
                return ResourceManager.GetString("BoxAbortProgramConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Automatic update failed!
        ///Please manually download the new version from lasergrbl site. 的本地化字符串。
        /// </summary>
        internal static string BoxAutoUpdateFailed {
            get {
                return ResourceManager.GetString("BoxAutoUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update require administrator privilege! 的本地化字符串。
        /// </summary>
        internal static string BoxAutoUpdateRequireAdmin {
            get {
                return ResourceManager.GetString("BoxAutoUpdateRequireAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update result 的本地化字符串。
        /// </summary>
        internal static string BoxAutoUpdateResult {
            get {
                return ResourceManager.GetString("BoxAutoUpdateResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Update success! 的本地化字符串。
        /// </summary>
        internal static string BoxAutoUpdateSuccess {
            get {
                return ResourceManager.GetString("BoxAutoUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There are some changes that have not been applied.
        ///Do you want to rewrite the configuration? 的本地化字符串。
        /// </summary>
        internal static string BoxConfigDetectedChanges {
            get {
                return ResourceManager.GetString("BoxConfigDetectedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Changes detected! 的本地化字符串。
        /// </summary>
        internal static string BoxConfigDetectedChangesTitle {
            get {
                return ResourceManager.GetString("BoxConfigDetectedChangesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot connect to device 的本地化字符串。
        /// </summary>
        internal static string BoxConnectErrorTitle {
            get {
                return ResourceManager.GetString("BoxConnectErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please provide GCode commands 的本地化字符串。
        /// </summary>
        internal static string BoxCustomButtonPleaseGCodeText {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseGCodeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please provide tooltip text 的本地化字符串。
        /// </summary>
        internal static string BoxCustomButtonPleaseToolTipText {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseToolTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Missing field 的本地化字符串。
        /// </summary>
        internal static string BoxCustomButtonPleaseToolTipTitle {
            get {
                return ResourceManager.GetString("BoxCustomButtonPleaseToolTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Are you sure to delete selected button? 的本地化字符串。
        /// </summary>
        internal static string BoxDeleteCustomButtonText {
            get {
                return ResourceManager.GetString("BoxDeleteCustomButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete custom button 的本地化字符串。
        /// </summary>
        internal static string BoxDeleteCustomButtonTitle {
            get {
                return ResourceManager.GetString("BoxDeleteCustomButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error exporting config! 的本地化字符串。
        /// </summary>
        internal static string BoxExportConfigError {
            get {
                return ResourceManager.GetString("BoxExportConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error 的本地化字符串。
        /// </summary>
        internal static string BoxExportConfigErrorTitle {
            get {
                return ResourceManager.GetString("BoxExportConfigErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File does not exist! 的本地化字符串。
        /// </summary>
        internal static string BoxExportConfigFileNotFound {
            get {
                return ResourceManager.GetString("BoxExportConfigFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Config exported successfully! 的本地化字符串。
        /// </summary>
        internal static string BoxExportConfigSuccess {
            get {
                return ResourceManager.GetString("BoxExportConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string BoxExportConfigSuccessTitle {
            get {
                return ResourceManager.GetString("BoxExportConfigSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error reading file! 的本地化字符串。
        /// </summary>
        internal static string BoxImportConfigFileError {
            get {
                return ResourceManager.GetString("BoxImportConfigFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Config imported with {1} errors! 的本地化字符串。
        /// </summary>
        internal static string BoxImportConfigWithError {
            get {
                return ResourceManager.GetString("BoxImportConfigWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Config imported successfully! 的本地化字符串。
        /// </summary>
        internal static string BoxImportConfigWithoutError {
            get {
                return ResourceManager.GetString("BoxImportConfigWithoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Import custom button 的本地化字符串。
        /// </summary>
        internal static string BoxImportCustomButtonCaption {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove actual buttons? Select yes to remove, no to keep. 的本地化字符串。
        /// </summary>
        internal static string BoxImportCustomButtonClearText {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonClearText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Confirmation 的本地化字符串。
        /// </summary>
        internal static string BoxImportCustomButtonrCaption {
            get {
                return ResourceManager.GetString("BoxImportCustomButtonrCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The engraver has some configuration parameters out of range. Please check machine configuration (menu &quot;Grbl&quot;, &quot;Grbl Configuration&quot;) parameters 130 and 131. 的本地化字符串。
        /// </summary>
        internal static string BoxMachineSizeOutOfRangeText {
            get {
                return ResourceManager.GetString("BoxMachineSizeOutOfRangeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string BoxMachineSizeOutOfRangeTitle {
            get {
                return ResourceManager.GetString("BoxMachineSizeOutOfRangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error reading config! 的本地化字符串。
        /// </summary>
        internal static string BoxReadConfigError {
            get {
                return ResourceManager.GetString("BoxReadConfigError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Showing cached values... 的本地化字符串。
        /// </summary>
        internal static string BoxReadConfigPleaseConnect {
            get {
                return ResourceManager.GetString("BoxReadConfigPleaseConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Config read successfully! 的本地化字符串。
        /// </summary>
        internal static string BoxReadConfigSuccess {
            get {
                return ResourceManager.GetString("BoxReadConfigSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Test notification has been sent, please check your phone! 的本地化字符串。
        /// </summary>
        internal static string BoxTelegramSettingText {
            get {
                return ResourceManager.GetString("BoxTelegramSettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Telegram notification 的本地化字符串。
        /// </summary>
        internal static string BoxTelegramSettingTitle {
            get {
                return ResourceManager.GetString("BoxTelegramSettingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No changes... nothing to write! 的本地化字符串。
        /// </summary>
        internal static string BoxWriteConfigNoChange {
            get {
                return ResourceManager.GetString("BoxWriteConfigNoChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Config written with {1} errors! 的本地化字符串。
        /// </summary>
        internal static string BoxWriteConfigWithError {
            get {
                return ResourceManager.GetString("BoxWriteConfigWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 {0} Config written successfully! 的本地化字符串。
        /// </summary>
        internal static string BoxWriteConfigWithoutError {
            get {
                return ResourceManager.GetString("BoxWriteConfigWithoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connect 的本地化字符串。
        /// </summary>
        internal static string BtnConnectTT {
            get {
                return ResourceManager.GetString("BtnConnectTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnect 的本地化字符串。
        /// </summary>
        internal static string BtnDisconnectTT {
            get {
                return ResourceManager.GetString("BtnDisconnectTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit button 的本地化字符串。
        /// </summary>
        internal static string CustomButtonEdit {
            get {
                return ResourceManager.GetString("CustomButtonEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Remove button 的本地化字符串。
        /// </summary>
        internal static string CustomButtonRemove {
            get {
                return ResourceManager.GetString("CustomButtonRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagonal (old) 的本地化字符串。
        /// </summary>
        internal static string DirectionDiagonal {
            get {
                return ResourceManager.GetString("DirectionDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal (old) 的本地化字符串。
        /// </summary>
        internal static string DirectionHorizontal {
            get {
                return ResourceManager.GetString("DirectionHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cross Fill 的本地化字符串。
        /// </summary>
        internal static string DirectionNewCross {
            get {
                return ResourceManager.GetString("DirectionNewCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagonal 的本地化字符串。
        /// </summary>
        internal static string DirectionNewDiagonal {
            get {
                return ResourceManager.GetString("DirectionNewDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagonal Cross Fill 的本地化字符串。
        /// </summary>
        internal static string DirectionNewDiagonalCross {
            get {
                return ResourceManager.GetString("DirectionNewDiagonalCross", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagonal Grid 的本地化字符串。
        /// </summary>
        internal static string DirectionNewDiagonalGrid {
            get {
                return ResourceManager.GetString("DirectionNewDiagonalGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Grid 的本地化字符串。
        /// </summary>
        internal static string DirectionNewGrid {
            get {
                return ResourceManager.GetString("DirectionNewGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hilbert 的本地化字符串。
        /// </summary>
        internal static string DirectionNewHilbert {
            get {
                return ResourceManager.GetString("DirectionNewHilbert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Horizontal 的本地化字符串。
        /// </summary>
        internal static string DirectionNewHorizontal {
            get {
                return ResourceManager.GetString("DirectionNewHorizontal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inset Filling 的本地化字符串。
        /// </summary>
        internal static string DirectionNewInsetFilling {
            get {
                return ResourceManager.GetString("DirectionNewInsetFilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Diagonal Reversed 的本地化字符串。
        /// </summary>
        internal static string DirectionNewReverseDiagonal {
            get {
                return ResourceManager.GetString("DirectionNewReverseDiagonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Squares 的本地化字符串。
        /// </summary>
        internal static string DirectionNewSquares {
            get {
                return ResourceManager.GetString("DirectionNewSquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical 的本地化字符串。
        /// </summary>
        internal static string DirectionNewVertical {
            get {
                return ResourceManager.GetString("DirectionNewVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Zig Zag 的本地化字符串。
        /// </summary>
        internal static string DirectionNewZigZag {
            get {
                return ResourceManager.GetString("DirectionNewZigZag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No Filling 的本地化字符串。
        /// </summary>
        internal static string DirectionNone {
            get {
                return ResourceManager.GetString("DirectionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Vertical (old) 的本地化字符串。
        /// </summary>
        internal static string DirectionVertical {
            get {
                return ResourceManager.GetString("DirectionVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File transfer in progress. Disconnect anyway? 的本地化字符串。
        /// </summary>
        internal static string DisconnectAnyway {
            get {
                return ResourceManager.GetString("DisconnectAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Dithering Options 的本地化字符串。
        /// </summary>
        internal static string DitheringOptions {
            get {
                return ResourceManager.GetString("DitheringOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 File transfer in progress. Exit anyway? 的本地化字符串。
        /// </summary>
        internal static string ExitAnyway {
            get {
                return ResourceManager.GetString("ExitAnyway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart required 的本地化字符串。
        /// </summary>
        internal static string FirmwareRequireRestart {
            get {
                return ResourceManager.GetString("FirmwareRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart is required to apply Firmware type changes. Restart now? 的本地化字符串。
        /// </summary>
        internal static string FirmwareRequireRestartNow {
            get {
                return ResourceManager.GetString("FirmwareRequireRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom 的本地化字符串。
        /// </summary>
        internal static string FormulaCustom {
            get {
                return ResourceManager.GetString("FormulaCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OpticalCorrect 的本地化字符串。
        /// </summary>
        internal static string FormulaOpticalCorrect {
            get {
                return ResourceManager.GetString("FormulaOpticalCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SimpleAverage 的本地化字符串。
        /// </summary>
        internal static string FormulaSimpleAverage {
            get {
                return ResourceManager.GetString("FormulaSimpleAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 WeightAverage 的本地化字符串。
        /// </summary>
        internal static string FormulaWeightAverage {
            get {
                return ResourceManager.GetString("FormulaWeightAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Smooth (HQ Bicubic) 的本地化字符串。
        /// </summary>
        internal static string InterpolationModeHighQualityBicubic {
            get {
                return ResourceManager.GetString("InterpolationModeHighQualityBicubic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sharp (NearestNeighbor) 的本地化字符串。
        /// </summary>
        internal static string InterpolationModeNearestNeighbor {
            get {
                return ResourceManager.GetString("InterpolationModeNearestNeighbor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Restart required 的本地化字符串。
        /// </summary>
        internal static string LanguageRequireRestart {
            get {
                return ResourceManager.GetString("LanguageRequireRestart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Require application restart, restart now? 的本地化字符串。
        /// </summary>
        internal static string LanguageRequireRestartNow {
            get {
                return ResourceManager.GetString("LanguageRequireRestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line To Line Options 的本地化字符串。
        /// </summary>
        internal static string Line2LineOptions {
            get {
                return ResourceManager.GetString("Line2LineOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Alarm 的本地化字符串。
        /// </summary>
        internal static string MacStatusAlarm {
            get {
                return ResourceManager.GetString("MacStatusAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Check 的本地化字符串。
        /// </summary>
        internal static string MacStatusCheck {
            get {
                return ResourceManager.GetString("MacStatusCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Connecting 的本地化字符串。
        /// </summary>
        internal static string MacStatusConnecting {
            get {
                return ResourceManager.GetString("MacStatusConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Disconnected 的本地化字符串。
        /// </summary>
        internal static string MacStatusDisconnected {
            get {
                return ResourceManager.GetString("MacStatusDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Door 的本地化字符串。
        /// </summary>
        internal static string MacStatusDoor {
            get {
                return ResourceManager.GetString("MacStatusDoor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hold 的本地化字符串。
        /// </summary>
        internal static string MacStatusHold {
            get {
                return ResourceManager.GetString("MacStatusHold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string MacStatusHome {
            get {
                return ResourceManager.GetString("MacStatusHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Idle 的本地化字符串。
        /// </summary>
        internal static string MacStatusIdle {
            get {
                return ResourceManager.GetString("MacStatusIdle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jog 的本地化字符串。
        /// </summary>
        internal static string MacStatusJog {
            get {
                return ResourceManager.GetString("MacStatusJog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run 的本地化字符串。
        /// </summary>
        internal static string MacStatusRun {
            get {
                return ResourceManager.GetString("MacStatusRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown 的本地化字符串。
        /// </summary>
        internal static string MacStatusUnknown {
            get {
                return ResourceManager.GetString("MacStatusUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Estimated Time: 的本地化字符串。
        /// </summary>
        internal static string MainFormEstimatedTime {
            get {
                return ResourceManager.GetString("MainFormEstimatedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Projected Time: 的本地化字符串。
        /// </summary>
        internal static string MainFormProjectedTime {
            get {
                return ResourceManager.GetString("MainFormProjectedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cannot open a new file now. 的本地化字符串。
        /// </summary>
        internal static string MsgboxCannotOpenFileNow {
            get {
                return ResourceManager.GetString("MsgboxCannotOpenFileNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap penImg {
            get {
                object obj = ResourceManager.GetObject("penImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 Error connecting your engraver.
        ///If you need help click on &quot;?&quot; button. 的本地化字符串。
        /// </summary>
        internal static string ProblemConnectingText {
            get {
                return ResourceManager.GetString("ProblemConnectingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Problem with connection? 的本地化字符串。
        /// </summary>
        internal static string ProblemConnectingTitle {
            get {
                return ResourceManager.GetString("ProblemConnectingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 It seems that the current position is no longer known by Grbl.
        ///Without the Homing Procedure ($H) the result may not be reliable.
        ///Continue anyway? 的本地化字符串。
        /// </summary>
        internal static string ResumeJobHomingRequired {
            get {
                return ResourceManager.GetString("ResumeJobHomingRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unknown position 的本地化字符串。
        /// </summary>
        internal static string ResumeJobHomingRequiredTitle {
            get {
                return ResourceManager.GetString("ResumeJobHomingRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Speed: 的本地化字符串。
        /// </summary>
        internal static string SpeedSliderToolTip {
            get {
                return ResourceManager.GetString("SpeedSliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Step: 的本地化字符串。
        /// </summary>
        internal static string StepSliderToolTip {
            get {
                return ResourceManager.GetString("StepSliderToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This file type is not supported. 的本地化字符串。
        /// </summary>
        internal static string UnsupportedFiletype {
            get {
                return ResourceManager.GetString("UnsupportedFiletype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 If the buffer is blocked, it is because there was some communication problem with your engraver. If you press &quot;OK&quot; LaserGRBL will ignore the full buffer and send the next commands. If this happens often, you should try to understand the causes of this problem.
        ///Click &quot;?&quot; for more information. 的本地化字符串。
        /// </summary>
        internal static string WarnBufferStuckUnlockText {
            get {
                return ResourceManager.GetString("WarnBufferStuckUnlockText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unlock buffer 的本地化字符串。
        /// </summary>
        internal static string WarnBufferStuckUnlockTitle {
            get {
                return ResourceManager.GetString("WarnBufferStuckUnlockTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Centerline option is not compatible with your PC.
        ///64bit OS is needed! 的本地化字符串。
        /// </summary>
        internal static string WarnCenterline64bit {
            get {
                return ResourceManager.GetString("WarnCenterline64bit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Line2Line option is not compatible with your engraver or with your configuration. PWM-able laser is needed, and PWM support should be enabled in LaserGRBL settings. 的本地化字符串。
        /// </summary>
        internal static string WarnLine2LinePWM {
            get {
                return ResourceManager.GetString("WarnLine2LinePWM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string WarnMessageBoxHeader {
            get {
                return ResourceManager.GetString("WarnMessageBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have set negative offsets, but your engraver is set to use positive space with soft limit alarm enabled ($20=1).
        ///
        ///This could generate a soft-limit error. Are you sure of the entered values? 的本地化字符串。
        /// </summary>
        internal static string WarnSoftLimitNS {
            get {
                return ResourceManager.GetString("WarnSoftLimitNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have set a size and offset that makes the job larger than the workspace configured in your engraver ({0}mm x {1}mm).
        ///Grbl Parameters $130 and $131.
        ///
        ///This could generate a soft-limit error or the machine could crash into the axes boundary. Are you sure of the entered values? 的本地化字符串。
        /// </summary>
        internal static string WarnSoftLimitOOB {
            get {
                return ResourceManager.GetString("WarnSoftLimitOOB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Job boundary confirmation 的本地化字符串。
        /// </summary>
        internal static string WarnSoftLimitTitle {
            get {
                return ResourceManager.GetString("WarnSoftLimitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Freely assigning the width and height of the work can lead to distortion of the image. Do you want to continue? 的本地化字符串。
        /// </summary>
        internal static string WarnUnlockProportionText {
            get {
                return ResourceManager.GetString("WarnUnlockProportionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string WarnUnlockProportionTitle {
            get {
                return ResourceManager.GetString("WarnUnlockProportionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &quot;M4 Dynamic Laser Power Mode&quot; has been set, but your engraver doesn&apos;t seem to support it.
        ///Only engravers with grbl version &gt;= 1.1 with &quot;laser mode&quot; enabled ($32=1) can take advantage of M4 option. 的本地化字符串。
        /// </summary>
        internal static string WarnWrongLaserMode {
            get {
                return ResourceManager.GetString("WarnWrongLaserMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Warning 的本地化字符串。
        /// </summary>
        internal static string WarnWrongLaserModeTitle {
            get {
                return ResourceManager.GetString("WarnWrongLaserModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap 校准机器位置 {
            get {
                object obj = ResourceManager.GetObject("校准机器位置", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PenImg
        {
            get
            {
                object obj = ResourceManager.GetObject("penImg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
